name: Browser Build
run-name: Build ${{ inputs.tag }} for ${{ inputs.release }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tor tag to build, example: tbb-13.5.8-build1"
        type: string
        required: true
      release:
        description: "Can be either: release or alpha"
        type: string
        required: true
jobs:

  browser-build:
    runs-on: self-hosted
    env:
        TAG: "${{inputs.tag}}"
        RELEASE: "${{inputs.release}}"
    timeout-minutes: 1440
    steps:

      - name: Clone browser-build repo
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Clone tor-browser-build
        run: scripts/clone_tor_browser_build.sh

      - name: Remove old logs and builds
        run: |
          rm -rf tor-browser-build/logs tor-browser-build/mullvadbrowser tor-browser-build/torbrowser checksums
          mkdir checksums

      - name: mullvadbrowser
        if: ${{  startsWith(inputs.tag, 'mb') }}
        run: scripts/build_mullvadbrowser.sh

      - name: torbrowser
        if: ${{  startsWith(inputs.tag, 'tbb') }}
        run: scripts/build_torbrowser.sh

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: checksums

      - name: Upload log files
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: tor-browser-build/logs
